### ISSUE TITLE
Interactive visualization of sonar data and geospatial location

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echoshader#18]
A lot of sonar data are collected on moving platforms (a ship or an autonomous surface vehicle -- USV/drone), so the data is inherently geospatial.

It will be cool to have something that allows scientists to interactively visualize both where the platform is and what the data looks like.

For example: in one panel users can pan a small window on a map where the ship track is plotted, and then in another panel the corresponding sonar data (echogram) is displayed.

The panels A and C in this figure below from a paper ([Della Penna and Gaube 2020](https://doi.org/10.3389/fmars.2020.00454)) is a _frozen_ illustration of how this might look like:

**A** shows the ship location, **C** shows the echogram (and B shows some an environmental parameter that is useful to understand this sonar observation data).

![ship-echogram](https://www.frontiersin.org/files/Articles/505214/fmars-07-00454-HTML/image_m/fmars-07-00454-g004.jpg)

**Comment by lendobo** [comment]
Hello!
While looking through this repo I found that all of these ideas look really engaging to work on (Especially this one). My question is: To what degree can we adapt the suggestions made here, since GSoC seems to discourage following ideas from the ideas list too closely? 
I feel that the developers would have the best understanding of the functionalities and what is actually needed of the package, in order to inform expansions.
Anyway, the "getting started" steps have been really helpful for familiarizing myself with this project, so thanks :)

**Comment by leewujung** [comment]
@lendobo : Welcome! Glad that you found the "getting started" steps helpful. 😄

We are fine with you adapting the ideas here, because we know that GSoC contributors would likely also have other ideas and/or bring up other alternative libraries/approaches. For example, once one starts to want to read in larger amounts of data to visualize, it is possible that the libraries we propose in these initial ideas could run into performance issues, and there may be paths to get around with it since this is a common needs. 

Not sure if this answers your question?

**Comment by lendobo** [comment]
@leewujung 
Thanks for the response! So the idea is that we would aim to get the desired functionality, such as visualizing platform location and corresponding data, but the exact approach (libraries etc.) is to be determined by the contributor, if I got that right.

**Comment by ldr426** [comment]
@lendobo 

hi, I am also one of the gsoc participant. You can call me Dingrui:smile:. 

I can give you one suggestion: Because the format of the data we are dealing with is nearly xarray, you'd better use a graphics library supporting xarray to avoid wasting memory in converting data format. 

Here are some plotting applications most used:

[Seaborn](https://seaborn.pydata.org/): “provides a high-level interface for drawing attractive statistical graphics.” Integrates well with pandas.

[HoloViews](https://holoviews.org/) and [GeoViews](https://geoviews.org/): “Composable, declarative data structures for building even complex visualizations easily.” Includes native support for xarray objects.

[Cartopy](https://scitools.org.uk/cartopy/docs/latest/): Provides cartographic tools.

**Comment by lendobo** [comment]
@ldr426 

Hi Dingrui :)
Awesome, thanks a lot for these suggestions, they give a great overview!

Cheers,
Marcello

**Comment by leewujung** [comment]
> So the idea is that we would aim to get the desired functionality, such as visualizing platform location and corresponding data, but the exact approach (libraries etc.) is to be determined by the contributor, if I got that right.

@lendobo : yes, because even though we (the mentors) collectively do have experience with the libraries we put into the ideas and have the vision for this project, there will always be unexpected challenges when actually implementing something. Or contributors may have other ideas of how to visualize sonar data after seeing the initial things we put in here. This makes it fun, and is also why GSoC encourages potential contributors to discuss things with mentors before writing a proposal. :)

**Comment by lendobo** [comment]
@leewujung 
Awesome, I like the sound of that :) 
The information provided in the paper definitely serves as a good inspiration / orientation for starting.

**Comment by bitanb1999** [comment]
Hello,
I am interested in contributing to GSoC 2022 and while going through this issue, I realized that the required visualization can very well be done with Seaborn and Cartopy. I went through the netCDF and Xarray documentation and saw they can be converted into CSV formats.  Does converting the data into CSV adulterate the dataset anyhow ? or does converting the dataset to CSV and then implementing the interactive viz using Plotly makes sense?
