### ISSUE TITLE
Refactor Map from Echogram and 2.5D Curtain; Create Echogram from Map 

### ISSUE THREAD

**Issue by ldr426** [OSOceanAcoustics/echoshader#80]
- [x] #111
- [x] #112
- [x] #113

Fisheries scientists often need to analyze the fish and zooplankton composition at specific geographic locations.
(Highlight Ship Track Section and Corresponding Echogram). Currently, echoshader visualizes ship tracks on a map based on gram range, but I find it challenging to understand the corresponding echograms for a particular section of the track (**reverse operation**). Therefore, I would like to propose a new feature that allows users to highlight a section of the ship track and view the corresponding echogram data.

Refactor https://github.com/OSOceanAcoustics/echoshader/issues/18 and https://github.com/OSOceanAcoustics/echoshader/issues/26 

User should be able to select a specific section of a ship track on the map.
Upon selecting the section, the corresponding echogram data should be displayed.

**Comment by leewujung** [comment]
Hey @ldr426 : How about breaking this issue up into 3 different issues? since they are related but each involves different work. You can hover mouse over each of the bullet points that click the upper-right corner to turn each into an issue, and this current one will be come the "tracking issue," which is nice. :)

**Comment by valentina-s** [comment]
All these are refactored in 0.1.0.
